<a href="https://colab.research.google.com/github/tejaswini-roopa/Email-Classification/blob/main/spam_ham.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**#importing packages**

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

**#import data**


---



In [5]:
spam_df=pd.read_csv('spam.csv')
print(spam_df)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


 **#inspect data**


In [6]:
spam_df.groupby('Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    641  Please call our customer service representativ...    4

**#turn spam/ham into numerical
 data,creating a new column called ‘spam’**

In [8]:
spam_df['spam']=spam_df['Category'].apply(lambda x:1 if x=='spam' else 0)

**#create train/test split**


In [9]:
x_train,x_test,y_train,y_test=train_test_split(spam_df.Message,spam_df.spam,test_size=0.25)


**#find word count and store data as a matrix**

In [12]:
cv=CountVectorizer()
x_train_count=cv.fit_transform(x_train.values)
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**#train model**

In [13]:
 model=MultinomialNB()
 model.fit(x_train_count,y_train)

MultinomialNB()

**#pre-test ham**

In [17]:
email_ham=["Free entry in 2 a wkly comp to win FA cup final"]
email_ham_count=cv.transform(email_ham)
model.predict(email_ham_count)

array([1])

**#pre-test spam**

In [19]:
email_spam=['reward money click']
email_spam_count=cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

**#test model**

In [20]:
x_test_count=cv.transform(x_test)
model.score(x_test_count,y_test)

0.9842067480258435